#!/bin/sh
set -e

KRILL_HOME="/var/lib/krill-sync/"
KRILL_USER="krillsync"

create_user() {
    if id ${KRILL_USER} > /dev/null 2>&1; then return; fi
    adduser --system --home "${KRILL_HOME}" --group ${KRILL_USER}
}

case "$1" in
configure)
    create_user
    ;;
esac

#DEBHELPER#
